name: TODO
on: [pull_request]

jobs:
  generate-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create TODO comments
        uses: gkampitakis/github-action-todo-commenter@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Au boulot ! :eyes:"
  ensure-completion:
    needs: comment
    runs-on: ubuntu-latest
    steps:
    - uses: adriangodong/actions-todo-bot@1.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
